### Get all
GET http://localhost:9998/api/posts

### Get by id
GET http://localhost:9998/api/posts/2

### save/update
POST http://localhost:9998/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "New Post"
}

### delete by id
DELETE http://localhost:9998/api/posts/2

